#!/usr/bin/env python3
"""Generate frontend/src/map/worldGrid.ts — a pixel land/sea bitmap.

One-off, dev-only tool. Runtime gains no dependency (the output is a static
TS bitmap). Run from the repo root:

    backend/.venv/bin/pip install global-land-mask numpy   # one time
    backend/.venv/bin/python frontend/scripts/gen_worldgrid.py

Resolution is WIDTH x HEIGHT cells. The grid is equirectangular and MUST match
the frontend's projection (src/map/projection.ts):
    x = (lon + 180) / 360   ->   lon = (col + 0.5)/WIDTH * 360 - 180
    y = (90 - lat) / 180     ->   lat = 90 - (row + 0.5)/HEIGHT * 180
so cell (col, row)'s centre is sampled against the land mask.
"""
from pathlib import Path

from global_land_mask import globe

WIDTH = 120
HEIGHT = 60
OUT = Path(__file__).resolve().parents[1] / "src" / "map" / "worldGrid.ts"


def build_rows() -> list[str]:
    rows: list[str] = []
    for row in range(HEIGHT):
        lat = 90.0 - (row + 0.5) / HEIGHT * 180.0
        cells = []
        for col in range(WIDTH):
            lon = (col + 0.5) / WIDTH * 360.0 - 180.0
            cells.append("#" if bool(globe.is_land(lat, lon)) else " ")
        rows.append("".join(cells))
    return rows


def render_ts(rows: list[str]) -> str:
    body = ",\n".join('  "' + r + '"' for r in rows)
    return (
        "// GENERATED by frontend/scripts/gen_worldgrid.py — do not edit by hand.\n"
        f"// Equirectangular land/sea grid ({WIDTH}x{HEIGHT}); '#' = land, ' ' = sea.\n"
        "// cols = lon -180..180 (west->east), rows = lat 90..-90 (north->south).\n"
        "// Sampled from the global-land-mask dataset; matches src/map/projection.ts.\n"
        "const RAW = [\n"
        f"{body},\n"
        "];\n"
        "const WIDTH = Math.max(...RAW.map((r) => r.length));\n"
        "const ROWS = RAW.map((r) => r.padEnd(WIDTH, ' '));\n\n"
        "export const GRID_ROWS = ROWS.length;\n"
        "export const GRID_COLS = WIDTH;\n\n"
        "export function isLand(col: number, row: number): boolean {\n"
        "  if (row < 0 || row >= GRID_ROWS || col < 0 || col >= GRID_COLS) return false;\n"
        '  return ROWS[row][col] === "#";\n'
        "}\n"
    )


def main() -> None:
    rows = build_rows()
    OUT.write_text(render_ts(rows))
    land = sum(line.count("#") for line in rows)
    total = WIDTH * HEIGHT
    print(f"wrote {OUT} ({WIDTH}x{HEIGHT}, {land}/{total} land cells, {land/total:.0%})")


if __name__ == "__main__":
    main()
